name: Deploy Orchestrator

# Triggered on pushes to main that affect the orchestrator or shared code
on:
  push:
    branches: [ main ]
    paths:
      - 'orchestrator/**'
      - 'shared/**'
      - '.github/workflows/deploy_orchestrator.yml'

jobs:
  # Use the reusable workflow to build and push the Docker image
  build-and-push:
    name: Build and Push Image
    uses: ./.github/workflows/build-and-push.yml
    with:
      context_dir: ./orchestrator
      image_name: orchestrator
      tag: ${{ github.sha }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  # Deploy the new image to Cloud Run
  deploy:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      # Set up Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ai-orchestrator
          region: ${{ secrets.GCP_REGION }}
          image: ${{ secrets.GCP_PROJECT_ID }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-ecosystem/orchestrator:${{ github.sha }}
      
      # Output the deployed service URL
      - name: Show Output
        run: |
          echo "Service URL: ${{ steps.deploy.outputs.url }}"
